[package]
name = "axum-examples"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.5.1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5.1", features = ["full"] }
