[package]
name = "sync-examples"
version.workspace = true
edition.workspace = true

[dependencies]
sync-core = { workspace = true }
tracing-subscriber = "0.3.18"
http = { version = "1.1.0", features = ["std"] }