[package]
name = "hyper-examples-1"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
http-body = "0.4"
bytes = "1"