[package]
name = "sync-core"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
http.workspace = true
http-body-util.workspace = true
bytes.workspace = true
hyper.workspace = true
route-recognizer.workspace = true
