[package]
name = "sync-core"
version.workspace = true
edition.workspace = true

[dependencies]
log = "0.4.22"
http.workspace = true
http-body-util.workspace = true
bytes.workspace = true
hyper.workspace = true
