name: Rustfmt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Run rustfmt
        run: |
          rustup component add rustfmt
          cargo fmt -- --check
      - name: Build
        run: |
          rustup component add rustfmt
          cargo build --verbose
      - name: Test
        run: |
          rustup component add rustfmt
          cargo test --verbose
